name: basic workflow

on:
  push:
    branches:
      - main
      - ajay

jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: testing
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          skip_install: false
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: install yarn && yarn run build
        run: yarn install && yarn run build
      
      - name: Upload file from Build to GCP Bucket
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: "build/"
          destination: xyzbucket-incometax123
          parent: false

        

